// Careers page — extra i18n strings
(function () {
  const extras = {
    zh: {
      "cr.eyebrow": "Careers",
      "cr.title":   "和我们一起,把视觉 AI 落到产线上",
      "cr.lead":    "凌柒科技正在扬州组建首批核心团队。如果你对工业视觉、深度学习、机器人感知有热情,我们想认识你。",
      "cr.p1.t":    "高速成长",
      "cr.p1.b":    "Day 1 就接触真实产线项目",
      "cr.p2.t":    "技术深度",
      "cr.p2.b":    "从经典 CV 到大模型全栈",
      "cr.p3.t":    "全球视野",
      "cr.p3.b":    "哈佛/宾大背景团队",
      "cr.p4.t":    "扬州为根",
      "cr.p4.b":    "享受扬州人才政策",

      "cr.jobs.eyebrow": "// Open Roles",
      "cr.jobs.title":   "正在招募",
      "cr.jobs.lead":    "所有职位 base 江苏扬州,部分岗位支持灵活办公。",
      "cr.apply":        "投递简历 →",

      "cr.j1.t":         "视觉算法工程师 (高级 / 中级)",
      "cr.j1.loc":       "扬州 / 全职",
      "cr.j1.headcount": "2 人",
      "cr.j1.salary":    "薪资面议",
      "cr.j1.desc":      "主导工业视觉 AOI 项目从需求到落地。负责 YOLO / CNN / 视觉大模型 (Qwen-VL / MiniCPM) 的训练、微调与部署。",
      "cr.j1.r1":        "3+ 年深度学习或机器视觉经验,熟悉 PyTorch / OpenCV",
      "cr.j1.r2":        "至少落地过一个工业视觉或医学影像项目",
      "cr.j1.r3":        "加分:大模型微调 (LoRA/QLoRA) / ONNX 边缘部署经验",

      "cr.j2.t":         "前端 / 全栈工程师",
      "cr.j2.loc":       "扬州 / 全职",
      "cr.j2.headcount": "1 人",
      "cr.j2.salary":    "薪资面议",
      "cr.j2.desc":      "负责 Web 端 AOI 检测平台、控制台、客户报表系统。把模型推理跑进浏览器(ONNX Runtime Web / WebGPU)。",
      "cr.j2.r1":        "2+ 年 React / Next.js 经验,熟悉 TypeScript",
      "cr.j2.r2":        "了解 Canvas / WebGL / 或 ONNX Runtime Web",
      "cr.j2.r3":        "加分:Tailwind / Framer Motion / 数据可视化",

      "cr.j3.t":         "硬件 / 产线集成工程师",
      "cr.j3.loc":       "扬州 + 客户现场出差",
      "cr.j3.headcount": "1 人",
      "cr.j3.salary":    "薪资面议",
      "cr.j3.desc":      "负责工业相机 / 镜头 / 光源选型,产线 AOI 系统集成调试,客户现场技术支持。",
      "cr.j3.r1":        "熟悉 GigE / USB3 工业相机、镜头光路设计",
      "cr.j3.r2":        "3+ 年产线集成或自动化设备经验",
      "cr.j3.r3":        "加分:PLC / SECS-GEM / 工厂 MES 集成经验",

      "cr.j4.t":         "BD / 客户成功",
      "cr.j4.loc":       "扬州 / 全职",
      "cr.j4.headcount": "1 人",
      "cr.j4.salary":    "薪资面议 + 提成",
      "cr.j4.desc":      "开拓扬州本地及长三角制造业客户,主导技术方案介绍 / POC 推进 / 商务谈判。客户成功:从 POC 到稳定交付的全程跟进。",
      "cr.j4.r1":        "3+ 年 to-B 销售或技术销售经验",
      "cr.j4.r2":        "能独立完成客户需求挖掘 / 方案讲解 / 报价",
      "cr.j4.r3":        "加分:制造业 / 自动化 / AI 行业资源",

      "cr.j5.t":         "实习生 · 算法 / 前端 / 数据标注",
      "cr.j5.loc":       "扬州 / 实习 (3-6 月)",
      "cr.j5.headcount": "2-3 人",
      "cr.j5.salary":    "日薪面议",
      "cr.j5.desc":      "面向计算机视觉 / AI / 软件相关专业在校生,提供真实产线项目实习机会,转正机会多。",
      "cr.j5.r1":        "本科及以上,计算机 / 自动化 / 电子等相关专业",
      "cr.j5.r2":        "每周可保证 4 天以上,实习时长 ≥ 3 个月",
      "cr.j5.r3":        "加分:有 GitHub 项目 / Kaggle 经历 / 数学基础扎实",

      "cr.cta.t":        "没看到合适的岗位?",
      "cr.cta.b":        "我们一直在寻找优秀的人。把简历发到下面的邮箱,标题写「自荐 · 你想做的方向」即可。",
      "cr.cta.btn":      "corporation@linqi.tech",
    },
    en: {
      "cr.eyebrow": "Careers",
      "cr.title":   "Help us bring visual AI to the factory floor",
      "cr.lead":    "We're building our founding team in Yangzhou. If you're passionate about industrial vision, deep learning, or robot perception — we'd like to talk.",
      "cr.p1.t":    "Fast growth",
      "cr.p1.b":    "Real production projects from day one",
      "cr.p2.t":    "Deep tech",
      "cr.p2.b":    "Classical CV to large vision-language models",
      "cr.p3.t":    "Global vision",
      "cr.p3.b":    "Harvard / UPenn-trained team",
      "cr.p4.t":    "Yangzhou-rooted",
      "cr.p4.b":    "Eligible for Yangzhou talent benefits",

      "cr.jobs.eyebrow": "// Open Roles",
      "cr.jobs.title":   "We're Hiring",
      "cr.jobs.lead":    "All roles based in Yangzhou, Jiangsu — some support flexible work.",
      "cr.apply":        "Apply now →",

      "cr.j1.t":         "Vision Algorithm Engineer (Senior / Mid)",
      "cr.j1.loc":       "Yangzhou / Full-time",
      "cr.j1.headcount": "2 openings",
      "cr.j1.salary":    "Competitive",
      "cr.j1.desc":      "Lead industrial-vision AOI projects end-to-end. Train and fine-tune YOLO / CNN / vision-language models (Qwen-VL / MiniCPM), deploy to production.",
      "cr.j1.r1":        "3+ years deep-learning or computer-vision experience; PyTorch + OpenCV",
      "cr.j1.r2":        "At least one shipped industrial-vision or medical-imaging project",
      "cr.j1.r3":        "Bonus: LoRA / QLoRA fine-tuning, ONNX edge deployment",

      "cr.j2.t":         "Frontend / Full-stack Engineer",
      "cr.j2.loc":       "Yangzhou / Full-time",
      "cr.j2.headcount": "1 opening",
      "cr.j2.salary":    "Competitive",
      "cr.j2.desc":      "Build the Web AOI inspection platform, dashboards, customer reports. Run model inference in the browser (ONNX Runtime Web / WebGPU).",
      "cr.j2.r1":        "2+ years React / Next.js + TypeScript",
      "cr.j2.r2":        "Familiarity with Canvas / WebGL / ONNX Runtime Web",
      "cr.j2.r3":        "Bonus: Tailwind / Framer Motion / data viz",

      "cr.j3.t":         "Hardware / Line-integration Engineer",
      "cr.j3.loc":       "Yangzhou + customer-site travel",
      "cr.j3.headcount": "1 opening",
      "cr.j3.salary":    "Competitive",
      "cr.j3.desc":      "Industrial camera / lens / lighting selection. AOI system integration on customer lines. On-site technical support.",
      "cr.j3.r1":        "Familiar with GigE / USB3 industrial cameras and optics",
      "cr.j3.r2":        "3+ years in line integration or automation equipment",
      "cr.j3.r3":        "Bonus: PLC / SECS-GEM / factory MES integration",

      "cr.j4.t":         "BD / Customer Success",
      "cr.j4.loc":       "Yangzhou / Full-time",
      "cr.j4.headcount": "1 opening",
      "cr.j4.salary":    "Competitive + commission",
      "cr.j4.desc":      "Develop Yangzhou and Yangtze-Delta manufacturing customers. Drive technical proposals, POC execution, deals. Customer success: from POC through steady delivery.",
      "cr.j4.r1":        "3+ years B2B sales or technical sales",
      "cr.j4.r2":        "Independent in needs discovery / pitching / pricing",
      "cr.j4.r3":        "Bonus: manufacturing / automation / AI industry network",

      "cr.j5.t":         "Intern · Algorithm / Frontend / Annotation",
      "cr.j5.loc":       "Yangzhou / Internship (3-6 mo)",
      "cr.j5.headcount": "2-3 openings",
      "cr.j5.salary":    "Daily rate",
      "cr.j5.desc":      "For CV / AI / software students. Real production projects, strong return-offer pipeline.",
      "cr.j5.r1":        "BS+ in CS / EE / Automation or related",
      "cr.j5.r2":        "4+ days/week, ≥ 3 months total",
      "cr.j5.r3":        "Bonus: GitHub projects / Kaggle / strong math",

      "cr.cta.t":        "Don't see the right role?",
      "cr.cta.b":        "We're always looking for great people. Send your resume to the address below, with subject line \"Open application · what you'd like to work on\".",
      "cr.cta.btn":      "corporation@linqi.tech",
    },
  };
  if (typeof I18N === "object") {
    Object.assign(I18N.zh, extras.zh);
    Object.assign(I18N.en, extras.en);
    const cur = document.documentElement.getAttribute("data-lang") || "zh";
    if (typeof applyLang === "function") applyLang(cur);
  }
})();
